"""
Step 3: TFLite INT8 Quantization
==================================
훈련된 모델을 ESP32용 TFLite INT8 형식으로 변환.

INT8 양자화 효과:
  - float32 → int8: 4배 크기 감소
  - 추론 속도 2-4배 향상 (정수 연산 가속)
  - 최소 정확도 손실 (post-training quantization)

실행:
  C:/Users/dwd00/anaconda3/envs/stetho_ai/python.exe quantize.py
"""

import os
import sys
import numpy as np
import tensorflow as tf

# ─── 경로 ────────────────────────────────────────────────────────────────────
BASE_DIR   = os.path.dirname(__file__)
DATA_DIR   = os.path.join(BASE_DIR, "data")
MODEL_DIR  = os.path.join(BASE_DIR, "models")
DEPLOY_DIR = os.path.join(BASE_DIR, "deploy")
os.makedirs(DEPLOY_DIR, exist_ok=True)

MODEL_PATH  = os.path.join(MODEL_DIR, "noise_gate_final.keras")
TFLITE_PATH = os.path.join(MODEL_DIR, "noise_gate.tflite")
C_HEADER    = os.path.join(DEPLOY_DIR, "model_data.h")


def get_representative_dataset():
    """
    대표 데이터셋 생성기 (INT8 양자화 캘리브레이션).
    학습 데이터 100개 샘플로 양자화 범위 결정.
    """
    X_train_path = os.path.join(DATA_DIR, "X_train.npy")
    if os.path.exists(X_train_path):
        X = np.load(X_train_path)
        indices = np.random.choice(len(X), min(200, len(X)), replace=False)
        samples = X[indices].astype(np.float32)
    else:
        # 학습 데이터 없으면 랜덤 샘플로 대체 (정확도 감소 가능)
        print("[WARN] 학습 데이터 없음, 랜덤 샘플로 캘리브레이션")
        samples = np.random.rand(200, 100, 1).astype(np.float32)

    def representative_dataset():
        for sample in samples:
            yield [sample[np.newaxis, :, :]]  # (1, 100, 1)

    return representative_dataset


def convert_to_tflite_int8(model_path, tflite_path):
    """
    Keras 모델 → TFLite INT8 변환.

    참고: Post-Training Integer Quantization
    https://www.tensorflow.org/lite/performance/post_training_integer_quant
    """
    print(f"모델 로드: {model_path}")
    model = tf.keras.models.load_model(model_path)

    # TFLite 컨버터 설정
    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    # INT8 양자화 옵션
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = get_representative_dataset()

    # 입출력도 INT8로 양자화 (ESP32 추론에 최적)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    print("INT8 양자화 변환 중...")
    tflite_model = converter.convert()

    # 저장
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"TFLite INT8 모델 저장: {tflite_path}")
    print(f"모델 크기: {size_kb:.1f} KB")
    return tflite_model


def validate_tflite(tflite_path):
    """양자화된 모델 정확도 검증."""
    X_val_path = os.path.join(DATA_DIR, "X_val.npy")
    y_val_path = os.path.join(DATA_DIR, "y_val.npy")
    if not os.path.exists(X_val_path):
        print("[WARN] 검증 데이터 없음, 검증 건너뜀")
        return

    X_val = np.load(X_val_path).astype(np.float32)
    y_val = np.load(y_val_path).astype(np.float32)

    # TFLite 인터프리터
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()

    input_details  = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # INT8 스케일/제로포인트 (입출력 변환에 필요)
    in_scale, in_zp   = input_details[0]["quantization"]
    out_scale, out_zp = output_details[0]["quantization"]

    correct = 0
    n_samples = min(500, len(X_val))

    for i in range(n_samples):
        # float32 → int8 변환
        x = X_val[i:i+1]  # (1, 100, 1)
        if in_scale != 0:
            x_int8 = np.clip(np.round(x / in_scale + in_zp), -128, 127).astype(np.int8)
        else:
            x_int8 = x.astype(np.int8)

        interpreter.set_tensor(input_details[0]["index"], x_int8)
        interpreter.invoke()

        out = interpreter.get_tensor(output_details[0]["index"])  # (1, 1) int8

        # int8 → float32 변환
        out_float = (out.astype(np.float32) - out_zp) * out_scale
        pred = 1 if out_float[0][0] > 0.5 else 0
        if pred == int(y_val[i]):
            correct += 1

    accuracy = correct / n_samples
    print(f"\nTFLite INT8 검증 정확도: {accuracy:.4f} ({accuracy*100:.1f}%)")
    print(f"(검증 샘플 {n_samples}개)")
    return accuracy


def generate_c_header(tflite_path, c_header_path):
    """
    TFLite 모델을 C 헤더 파일로 변환 (ESP32 펌웨어 임베딩용).

    ESP32 Arduino/IDF에서 PROGMEM 또는 flash 배열로 사용.
    """
    with open(tflite_path, "rb") as f:
        model_data = f.read()

    lines = [
        "// Auto-generated by quantize.py",
        "// TFLite INT8 Noise Gate Model for On-Device BPM Detection",
        "// Input:  (1, 100, 1) int8 - Shannon Energy Envelope (1sec @ 10ms/frame)",
        "// Output: (1, 1) int8 - heart sound probability",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"const uint32_t g_noise_gate_model_len = {len(model_data)};",
        "",
        "// Store in flash memory (ESP32: DRAM_ATTR or PROGMEM)",
        "alignas(8) const uint8_t g_noise_gate_model_data[] = {",
    ]

    # 16바이트씩 hex 출력
    hex_values = []
    for i, byte in enumerate(model_data):
        hex_values.append(f"0x{byte:02x}")

    chunks = [hex_values[i:i+16] for i in range(0, len(hex_values), 16)]
    for chunk in chunks:
        lines.append("  " + ", ".join(chunk) + ",")

    lines.append("};")

    with open(c_header_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nC 헤더 저장: {c_header_path}")
    print(f"  크기: {len(model_data):,} bytes")
    print(f"  ESP32 Flash에 저장 시 DRAM 미사용")


def main():
    print("=" * 60)
    print("TFLite INT8 양자화 변환")
    print("=" * 60)

    if not os.path.exists(MODEL_PATH):
        print(f"[ERROR] 모델 파일 없음: {MODEL_PATH}")
        print("먼저 train.py를 실행하세요.")
        sys.exit(1)

    # 1. INT8 변환
    print("\n[1/3] TFLite INT8 변환...")
    tflite_model = convert_to_tflite_int8(MODEL_PATH, TFLITE_PATH)

    # 2. 정확도 검증
    print("\n[2/3] 양자화 정확도 검증...")
    validate_tflite(TFLITE_PATH)

    # 3. C 헤더 생성
    print("\n[3/3] C 헤더 파일 생성...")
    generate_c_header(TFLITE_PATH, C_HEADER)

    print("\n" + "=" * 60)
    print("완료!")
    print(f"TFLite 모델:  {TFLITE_PATH}")
    print(f"C 헤더:       {C_HEADER}")
    print("\n다음 단계:")
    print("  1. python bpm_test.py - PC에서 BPM 정확도 테스트")
    print("  2. deploy/BPMDetector.h - ESP32 펌웨어에 통합")


if __name__ == "__main__":
    main()
